### PR TITLE
Update the README file

### PR DESCRIPTION
**Pull request by iacopomasi**
Adding the Florence 2D/3D hybrid face dataset

### CODE REVIEW

**Comment by BernhardEgger** [comment]
This looks interesting and relevant, but I tried both links and I cannot access the preview of the dataset or the final dataset.
http://www.micc.uniﬁ.it/masi/research/ﬀd
http://www.micc.uniﬁ.it/datasets/3d-faces

**Comment by iacopomasi** [comment]
This is the link I added [http://www.micc.unifi.it/vim/3dfaces-dataset/index.html](http://www.micc.unifi.it/vim/3dfaces-dataset/index.html) I am able to inspect the model and request the dataset from here. (in order to get the dataset you have to fill an agreement). Please, see top right part of the website.

image

Are you able to see this link?

Thank you.

**Comment by BernhardEgger** [comment]
Sorry, my fault, I google searched instead of following the link and ended up here:
http://www.micc.unifi.it/blog/intelligent-videosurveillance/the-florence-2d3d-hybrid-face-dataset

Thanks for adding the link :)

**Comment by iacopomasi** [comment]
No problem and thank you for adding it!

**Pull request merged**
